global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Logging;
global using Ordering.Orders.Events;
global using Ordering.Orders.Models;
global using Ordering.Orders.ValueObjects;
global using Shared.DDD;
global using System.Reflection;
